### ISSUE TITLE
ERR_BAD_REQUEST, feedUrlsList.txt not generated as a result

### ISSUE THREAD

**Issue by roitsuku** [stechermichal/mangadex-rss#1]
Hi there,
I juste tried to run your code on my machine, but I get an ERR_BAD_REQUEST.

1. I installed nodejs + npm
2. I edited the config.ts to set my mangadex credentials
3. I ran ./run.sh

Here is the console output, I replaced my mangadex credentials with "MY_USERNAME" and "MY_PASSWORD".
Do you have an idea of what's going wrong and if I missed something ? It fails before the "feedUrlsList.txt" file creation instruction, as the file is never created.

Thanks for your time !

> [] $ ./run.sh 
> Installing project dependencies...
> 
> up to date, audited 41 packages in 517ms
> 
> 2 packages are looking for funding
>   run `npm fund` for details
> 
> found 0 vulnerabilities
> Compiling TypeScript to JavaScript...
> Running JavaScript code...
> AxiosError: Request failed with status code 401
>     at settle (/home/loicd/mangadex-rss/node_modules/axios/dist/node/axios.cjs:1909:12)
>     at IncomingMessage.handleStreamEnd (/home/loicd/mangadex-rss/node_modules/axios/dist/node/axios.cjs:2989:11)
>     at IncomingMessage.emit (node:events:526:35)
>     at endReadableNT (node:internal/streams/readable:1376:12)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
>   code: 'ERR_BAD_REQUEST',
>   config: {
>     transitional: {
>       silentJSONParsing: true,
>       forcedJSONParsing: true,
>       clarifyTimeoutError: false
>     },
>     adapter: [ 'xhr', 'http' ],
>     transformRequest: [ [Function: transformRequest] ],
>     transformResponse: [ [Function: transformResponse] ],
>     timeout: 0,
>     xsrfCookieName: 'XSRF-TOKEN',
>     xsrfHeaderName: 'X-XSRF-TOKEN',
>     maxContentLength: -1,
>     maxBodyLength: -1,
>     env: { FormData: [Function], Blob: [class Blob] },
>     validateStatus: [Function: validateStatus],
>     headers: AxiosHeaders {
>       Accept: 'application/json, text/plain, */*',
>       'Content-Type': 'application/json',
>       'User-Agent': 'axios/1.4.0',
>       'Content-Length': '46',
>       'Accept-Encoding': 'gzip, compress, deflate, br'
>     },
>     method: 'post',
>     url: 'https://api.mangadex.org/auth/login',
>     data: '{"username":"MY_USERNAME","password":"MY_PASSWORD"}'
>   },
>   request: <ref *1> ClientRequest {
>     _events: [Object: null prototype] {
>       abort: [Function (anonymous)],
>       aborted: [Function (anonymous)],
>       connect: [Function (anonymous)],
>       error: [Function (anonymous)],
>       socket: [Function (anonymous)],
>       timeout: [Function (anonymous)],
>       finish: [Function: requestOnFinish]
>     },
>     _eventsCount: 7,
>     _maxListeners: undefined,
>     outputData: [],
>     outputSize: 0,
>     writable: true,
>     destroyed: true,
>     _last: false,
>     chunkedEncoding: false,
>     shouldKeepAlive: true,
>     maxRequestsOnConnectionReached: false,
>     _defaultKeepAlive: true,
>     useChunkedEncodingByDefault: true,
>     sendDate: false,
>     _removedConnection: false,
>     _removedContLen: false,
>     _removedTE: false,
>     strictContentLength: false,
>     _contentLength: '46',
>     _hasBody: true,
>     _trailer: '',
>     finished: true,
>     _headerSent: true,
>     _closed: true,
>     socket: TLSSocket {
>       _tlsOptions: [Object],
>       _secureEstablished: true,
>       _securePending: false,
>       _newSessionPending: false,
>       _controlReleased: true,
>       secureConnecting: false,
>       _SNICallback: null,
>       servername: 'api.mangadex.org',
>       alpnProtocol: false,
>       authorized: true,
>       authorizationError: null,
>       encrypted: true,
>       _events: [Object: null prototype],
>       _eventsCount: 9,
>       connecting: false,
>       _hadError: false,
>       _parent: null,
>       _host: 'api.mangadex.org',
>       _closeAfterHandlingError: false,
>       _readableState: [ReadableState],
>       _maxListeners: undefined,
>       _writableState: [WritableState],
>       allowHalfOpen: false,
>       _sockname: null,
>       _pendingData: null,
>       _pendingEncoding: '',
>       server: undefined,
>       _server: null,
>       ssl: [TLSWrap],
>       _requestCert: true,
>       _rejectUnauthorized: true,
>       timeout: 5000,
>       parser: null,
>       _httpMessage: null,
>       autoSelectFamilyAttemptedAddresses: [Array],
>       [Symbol(alpncallback)]: null,
>       [Symbol(res)]: [TLSWrap],
>       [Symbol(verified)]: true,
>       [Symbol(pendingSession)]: null,
>       [Symbol(async_id_symbol)]: -1,
>       [Symbol(kHandle)]: [TLSWrap],
>       [Symbol(lastWriteQueueSize)]: 0,
>       [Symbol(timeout)]: Timeout {
>         _idleTimeout: 5000,
>         _idlePrev: [TimersList],
>         _idleNext: [TimersList],
>         _idleStart: 524,
>         _onTimeout: [Function: bound ],
>         _timerArgs: undefined,
>         _repeat: null,
>         _destroyed: false,
>         [Symbol(refed)]: false,
>         [Symbol(kHasPrimitive)]: false,
>         [Symbol(asyncId)]: 26,
>         [Symbol(triggerId)]: 24
>       },
>       [Symbol(kBuffer)]: null,
>       [Symbol(kBufferCb)]: null,
>       [Symbol(kBufferGen)]: null,
>       [Symbol(kCapture)]: false,
>       [Symbol(kSetNoDelay)]: false,
>       [Symbol(kSetKeepAlive)]: true,
>       [Symbol(kSetKeepAliveInitialDelay)]: 1,
>       [Symbol(kBytesRead)]: 0,
>       [Symbol(kBytesWritten)]: 0,
>       [Symbol(connect-options)]: [Object]
>     },
>     _header: 'POST /auth/login HTTP/1.1\r\n' +
>       'Accept: application/json, text/plain, */*\r\n' +
>       'Content-Type: application/json\r\n' +
>       'User-Agent: axios/1.4.0\r\n' +
>       'Content-Length: 46\r\n' +
>       'Accept-Encoding: gzip, compress, deflate, br\r\n' +
>       'Host: api.mangadex.org\r\n' +
>       'Connection: keep-alive\r\n' +
>       '\r\n',
>     _keepAliveTimeout: 0,
>     _onPendingData: [Function: nop],
>     agent: Agent {
>       _events: [Object: null prototype],
>       _eventsCount: 2,
>       _maxListeners: undefined,
>       defaultPort: 443,
>       protocol: 'https:',
>       options: [Object: null prototype],
>       requests: [Object: null prototype] {},
>       sockets: [Object: null prototype] {},
>       freeSockets: [Object: null prototype],
>       keepAliveMsecs: 1000,
>       keepAlive: true,
>       maxSockets: Infinity,
>       maxFreeSockets: 256,
>       scheduling: 'lifo',
>       maxTotalSockets: Infinity,
>       totalSocketCount: 1,
>       maxCachedSessions: 100,
>       _sessionCache: [Object],
>       [Symbol(kCapture)]: false
>     },
>     socketPath: undefined,
>     method: 'POST',
>     maxHeaderSize: undefined,
>     insecureHTTPParser: undefined,
>     joinDuplicateHeaders: undefined,
>     path: '/auth/login',
>     _ended: true,
>     res: IncomingMessage {
>       _readableState: [ReadableState],
>       _events: [Object: null prototype],
>       _eventsCount: 4,
>       _maxListeners: undefined,
>       socket: null,
>       httpVersionMajor: 1,
>       httpVersionMinor: 1,
>       httpVersion: '1.1',
>       complete: true,
>       rawHeaders: [Array],
>       rawTrailers: [],
>       joinDuplicateHeaders: undefined,
>       aborted: false,
>       upgrade: false,
>       url: '',
>       method: null,
>       statusCode: 401,
>       statusMessage: 'Unauthorized',
>       client: [TLSSocket],
>       _consuming: false,
>       _dumped: false,
>       req: [Circular *1],
>       responseUrl: 'https://api.mangadex.org/auth/login',
>       redirects: [],
>       [Symbol(kCapture)]: false,
>       [Symbol(kHeaders)]: [Object],
>       [Symbol(kHeadersCount)]: 50,
>       [Symbol(kTrailers)]: null,
>       [Symbol(kTrailersCount)]: 0
>     },
>     aborted: false,
>     timeoutCb: null,
>     upgradeOrConnect: false,
>     parser: null,
>     maxHeadersCount: null,
>     reusedSocket: false,
>     host: 'api.mangadex.org',
>     protocol: 'https:',
>     _redirectable: Writable {
>       _writableState: [WritableState],
>       _events: [Object: null prototype],
>       _eventsCount: 3,
>       _maxListeners: undefined,
>       _options: [Object],
>       _ended: true,
>       _ending: true,
>       _redirectCount: 0,
>       _redirects: [],
>       _requestBodyLength: 46,
>       _requestBodyBuffers: [],
>       _onNativeResponse: [Function (anonymous)],
>       _currentRequest: [Circular *1],
>       _currentUrl: 'https://api.mangadex.org/auth/login',
>       [Symbol(kCapture)]: false
>     },
>     [Symbol(kCapture)]: false,
>     [Symbol(kBytesWritten)]: 0,
>     [Symbol(kNeedDrain)]: false,
>     [Symbol(corked)]: 0,
>     [Symbol(kOutHeaders)]: [Object: null prototype] {
>       accept: [Array],
>       'content-type': [Array],
>       'user-agent': [Array],
>       'content-length': [Array],
>       'accept-encoding': [Array],
>       host: [Array]
>     },
>     [Symbol(errored)]: null,
>     [Symbol(kHighWaterMark)]: 16384,
>     [Symbol(kRejectNonStandardBodyWrites)]: false,
>     [Symbol(kUniqueHeaders)]: null
>   },
>   response: {
>     status: 401,
>     statusText: 'Unauthorized',
>     headers: AxiosHeaders {
>       'content-type': 'application/json',
>       'cache-control': 'no-cache, private',
>       date: 'Mon, 04 Sep 2023 20:10:03 GMT',
>       'www-authenticate': 'Bearer',
>       'x-ratelimit-remaining': '23',
>       'x-ratelimit-retry-after': '1693860686',
>       'x-ratelimit-limit': '30',
>       'x-cache': 'PASS',
>       'content-length': '184',
>       'access-control-allow-credentials': 'true',
>       'access-control-expose-headers': '*',
>       vary: 'Origin',
>       server: 'MangaDex',
>       via: 'HTTP/1.1 EU-CENTRAL-D1x1',
>       'x-request-id': '196065b2-7de2-4c72-a44a-44080076a7f9',
>       'permissions-policy': 'fullscreen=(self)',
>       'referrer-policy': 'strict-origin',
>       'x-content-type-options': 'nosniff',
>       'x-xss-protection': '1; mode=block',
>       'x-frame-options': 'DENY',
>       'cross-origin-embedder-policy': 'unsafe-none',
>       'cross-origin-opener-policy': 'same-origin-allow-popups',
>       'cross-origin-resource-policy': 'cross-origin',
>       'strict-transport-security': 'max-age=63072000; includeSubDomains; preload',
>       'alt-svc': 'h3=":443"; ma=86400'
>     },
>     config: {
>       transitional: [Object],
>       adapter: [Array],
>       transformRequest: [Array],
>       transformResponse: [Array],
>       timeout: 0,
>       xsrfCookieName: 'XSRF-TOKEN',
>       xsrfHeaderName: 'X-XSRF-TOKEN',
>       maxContentLength: -1,
>       maxBodyLength: -1,
>       env: [Object],
>       validateStatus: [Function: validateStatus],
>       headers: [AxiosHeaders],
>       method: 'post',
>       url: 'https://api.mangadex.org/auth/login',
>       data: '{"username":"MY_USERNAME","password":"MY_PASSWORD"}'
>     },
>     request: <ref *1> ClientRequest {
>       _events: [Object: null prototype],
>       _eventsCount: 7,
>       _maxListeners: undefined,
>       outputData: [],
>       outputSize: 0,
>       writable: true,
>       destroyed: true,
>       _last: false,
>       chunkedEncoding: false,
>       shouldKeepAlive: true,
>       maxRequestsOnConnectionReached: false,
>       _defaultKeepAlive: true,
>       useChunkedEncodingByDefault: true,
>       sendDate: false,
>       _removedConnection: false,
>       _removedContLen: false,
>       _removedTE: false,
>       strictContentLength: false,
>       _contentLength: '46',
>       _hasBody: true,
>       _trailer: '',
>       finished: true,
>       _headerSent: true,
>       _closed: true,
>       socket: [TLSSocket],
>       _header: 'POST /auth/login HTTP/1.1\r\n' +
>         'Accept: application/json, text/plain, */*\r\n' +
>         'Content-Type: application/json\r\n' +
>         'User-Agent: axios/1.4.0\r\n' +
>         'Content-Length: 46\r\n' +
>         'Accept-Encoding: gzip, compress, deflate, br\r\n' +
>         'Host: api.mangadex.org\r\n' +
>         'Connection: keep-alive\r\n' +
>         '\r\n',
>       _keepAliveTimeout: 0,
>       _onPendingData: [Function: nop],
>       agent: [Agent],
>       socketPath: undefined,
>       method: 'POST',
>       maxHeaderSize: undefined,
>       insecureHTTPParser: undefined,
>       joinDuplicateHeaders: undefined,
>       path: '/auth/login',
>       _ended: true,
>       res: [IncomingMessage],
>       aborted: false,
>       timeoutCb: null,
>       upgradeOrConnect: false,
>       parser: null,
>       maxHeadersCount: null,
>       reusedSocket: false,
>       host: 'api.mangadex.org',
>       protocol: 'https:',
>       _redirectable: [Writable],
>       [Symbol(kCapture)]: false,
>       [Symbol(kBytesWritten)]: 0,
>       [Symbol(kNeedDrain)]: false,
>       [Symbol(corked)]: 0,
>       [Symbol(kOutHeaders)]: [Object: null prototype],
>       [Symbol(errored)]: null,
>       [Symbol(kHighWaterMark)]: 16384,
>       [Symbol(kRejectNonStandardBodyWrites)]: false,
>       [Symbol(kUniqueHeaders)]: null
>     },
>     data: { result: 'error', errors: [Array] }
>   }
> }
> Success! Your feed URLs have been generated.
> []$

**Comment by stechermichal** [comment]
@roitsuku Sorry for the late reaction, not sure how/why my notifications for this repo were turned off.

The error is something with authentication, but I'm going to assume you haven't entered the username/password wrong, given that you took the time to post this issue and redacted the credentials in the stack trace too.


I wasn't able to replicate it though, will keep trying though.

**Comment by stechermichal** [comment]
Apparently this is an issue with mangadex changing their authentication API - this affects only accounts created after December 2022 (or changed password past that date).

They have not yet released a public client replacement. I will make changes that use personal client soon, but it will complicate it for everyone involved as that means the user has to request one in their account settings and wait for a manual approvement.

**Comment by stechermichal** [comment]
Fixed by changing how auth is done in #3
