### ISSUE TITLE
help-wanted  which rss tool do you use ? 

### ISSUE THREAD

**Issue by MaxEhrhart** [stechermichal/mangadex-rss#4]
Hi!
first of all, i have discovered your work recently and since the mangadex migration i have been looking for another way to use rss again. really liked your tool! thanks 👍  

now, i am not an experienced rss user, i have a simple question ...
how can i import all feeds at once?

i tried using raven and rss guardian, opera browser default rss, etc...
do i have to open the file and import one by one?
i have 500+ manga im reading, is there a quick way to do it?
which tool do you use?

thanks for your work

**Comment by stechermichal** [comment]
I see, that's fairly annoying for you if you follow 500, sorry about that. The thing that this uses "under the hood": https://mdrss.tijlvdb.me
allows only up to 10 titles being combined into one link. 

You should end up with a file called feedUrls.json, which for you, would contain 50 URLs, where each will look something like this:
https://mdrss.tijlvdb.me/feed?q=manga:fdb14889-59ef-48dd-a883-7558f04c2060,tl:en&q=manga:fc4eede2-4fc9-4fdc-8904-7ea7ae56d773,tl:en&q=manga:ebff8638-a79f-4ddc-b754-3662bbbf4bd3,tl:en except with 10 manga IDs per link.

So for me with 100 follows it wasn't that much of a big deal to add 10 sources where each contains one of the generated URLs. That's obviously a buncha more work with 50.

The only solution I can think of is using rss that accepts imports via OPML. Create a file called feeds.opml and populate it with the generated URLs:
```
<?xml version="1.0" encoding="UTF-8"?>
<opml version="1.0">
  <head>
    <title>My RSS Feeds</title>
  </head>
  <body>
    <outline text="Feed 1" xmlUrl="generated URL 1 here"/>
    <outline text="Feed 2" xmlUrl="generated URL 2 here"/>
    <!-- Add more feeds here -->
  </body>
</opml>
```


Never used it personally, supposedly Inoreader and Feedly support this and it's still a bunch or work and you are still pasting in the 50URLs one way or another, but that's the best I can think of.
